// Code generated by goctl. DO NOT EDIT.
package types

type LoginRequest struct {
	Name     string `path:"name"`
	Password string `path:"password"`
}

type LoginResponse struct {
	Token string `json:"token"`
}
